<?php
/**
 * MenuItem
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Grab\GrabfoodApiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Grab\GrabfoodApiSdk\Model;

use \ArrayAccess;
use \Grab\GrabfoodApiSdk\ObjectSerializer;

/**
 * MenuItem Class Doc Comment
 *
 * @category Class
 * @package  Grab\GrabfoodApiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MenuItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'MenuItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'name' => 'string',
        'name_translation' => 'array<string,string>',
        'available_status' => 'string',
        'description' => 'string',
        'description_translation' => 'array<string,string>',
        'price' => 'int',
        'photos' => 'string[]',
        'special_type' => 'string',
        'taxable' => 'bool',
        'barcode' => 'string',
        'selling_time_id' => 'string',
        'max_stock' => 'int',
        'sequence' => 'int',
        'advanced_pricing' => '\Grab\GrabfoodApiSdk\Model\AdvancedPricing',
        'purchasability' => '\Grab\GrabfoodApiSdk\Model\Purchasability',
        'modifier_groups' => '\Grab\GrabfoodApiSdk\Model\ModifierGroup[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'name' => null,
        'name_translation' => null,
        'available_status' => null,
        'description' => null,
        'description_translation' => null,
        'price' => 'int64',
        'photos' => null,
        'special_type' => null,
        'taxable' => null,
        'barcode' => null,
        'selling_time_id' => null,
        'max_stock' => 'int64',
        'sequence' => null,
        'advanced_pricing' => null,
        'purchasability' => null,
        'modifier_groups' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'name_translation' => false,
        'available_status' => false,
        'description' => false,
        'description_translation' => false,
        'price' => false,
        'photos' => false,
        'special_type' => false,
        'taxable' => false,
        'barcode' => false,
        'selling_time_id' => false,
        'max_stock' => false,
        'sequence' => false,
        'advanced_pricing' => false,
        'purchasability' => false,
        'modifier_groups' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'name_translation' => 'nameTranslation',
        'available_status' => 'availableStatus',
        'description' => 'description',
        'description_translation' => 'descriptionTranslation',
        'price' => 'price',
        'photos' => 'photos',
        'special_type' => 'specialType',
        'taxable' => 'taxable',
        'barcode' => 'barcode',
        'selling_time_id' => 'sellingTimeID',
        'max_stock' => 'maxStock',
        'sequence' => 'sequence',
        'advanced_pricing' => 'advancedPricing',
        'purchasability' => 'purchasability',
        'modifier_groups' => 'modifierGroups'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'name_translation' => 'setNameTranslation',
        'available_status' => 'setAvailableStatus',
        'description' => 'setDescription',
        'description_translation' => 'setDescriptionTranslation',
        'price' => 'setPrice',
        'photos' => 'setPhotos',
        'special_type' => 'setSpecialType',
        'taxable' => 'setTaxable',
        'barcode' => 'setBarcode',
        'selling_time_id' => 'setSellingTimeId',
        'max_stock' => 'setMaxStock',
        'sequence' => 'setSequence',
        'advanced_pricing' => 'setAdvancedPricing',
        'purchasability' => 'setPurchasability',
        'modifier_groups' => 'setModifierGroups'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'name_translation' => 'getNameTranslation',
        'available_status' => 'getAvailableStatus',
        'description' => 'getDescription',
        'description_translation' => 'getDescriptionTranslation',
        'price' => 'getPrice',
        'photos' => 'getPhotos',
        'special_type' => 'getSpecialType',
        'taxable' => 'getTaxable',
        'barcode' => 'getBarcode',
        'selling_time_id' => 'getSellingTimeId',
        'max_stock' => 'getMaxStock',
        'sequence' => 'getSequence',
        'advanced_pricing' => 'getAdvancedPricing',
        'purchasability' => 'getPurchasability',
        'modifier_groups' => 'getModifierGroups'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const AVAILABLE_STATUS_AVAILABLE = 'AVAILABLE';
    public const AVAILABLE_STATUS_UNAVAILABLE = 'UNAVAILABLE';
    public const AVAILABLE_STATUS_HIDE = 'HIDE';
    public const AVAILABLE_STATUS_UNAVAILABLETODAY = 'UNAVAILABLETODAY';
    public const AVAILABLE_STATUS_UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';
    public const SPECIAL_TYPE_ALCOHOL = 'alcohol';
    public const SPECIAL_TYPE_EMPTY = '';
    public const SPECIAL_TYPE_UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAvailableStatusAllowableValues()
    {
        return [
            self::AVAILABLE_STATUS_AVAILABLE,
            self::AVAILABLE_STATUS_UNAVAILABLE,
            self::AVAILABLE_STATUS_HIDE,
            self::AVAILABLE_STATUS_UNAVAILABLETODAY,
            self::AVAILABLE_STATUS_UNKNOWN_DEFAULT_OPEN_API,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSpecialTypeAllowableValues()
    {
        return [
            self::SPECIAL_TYPE_ALCOHOL,
            self::SPECIAL_TYPE_EMPTY,
            self::SPECIAL_TYPE_UNKNOWN_DEFAULT_OPEN_API,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('name_translation', $data ?? [], null);
        $this->setIfExists('available_status', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('description_translation', $data ?? [], null);
        $this->setIfExists('price', $data ?? [], null);
        $this->setIfExists('photos', $data ?? [], null);
        $this->setIfExists('special_type', $data ?? [], null);
        $this->setIfExists('taxable', $data ?? [], null);
        $this->setIfExists('barcode', $data ?? [], null);
        $this->setIfExists('selling_time_id', $data ?? [], null);
        $this->setIfExists('max_stock', $data ?? [], null);
        $this->setIfExists('sequence', $data ?? [], null);
        $this->setIfExists('advanced_pricing', $data ?? [], null);
        $this->setIfExists('purchasability', $data ?? [], null);
        $this->setIfExists('modifier_groups', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ((mb_strlen($this->container['id']) > 64)) {
            $invalidProperties[] = "invalid value for 'id', the character length must be smaller than or equal to 64.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 80)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 80.";
        }

        if ($this->container['available_status'] === null) {
            $invalidProperties[] = "'available_status' can't be null";
        }
        $allowedValues = $this->getAvailableStatusAllowableValues();
        if (!is_null($this->container['available_status']) && !in_array($this->container['available_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'available_status', must be one of '%s'",
                $this->container['available_status'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['description']) && (mb_strlen($this->container['description']) > 300)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be smaller than or equal to 300.";
        }

        if ($this->container['price'] === null) {
            $invalidProperties[] = "'price' can't be null";
        }
        $allowedValues = $this->getSpecialTypeAllowableValues();
        if (!is_null($this->container['special_type']) && !in_array($this->container['special_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'special_type', must be one of '%s'",
                $this->container['special_type'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['barcode']) && (mb_strlen($this->container['barcode']) > 64)) {
            $invalidProperties[] = "invalid value for 'barcode', the character length must be smaller than or equal to 64.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id The item's ID in the partner system. This ID should be unique.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        if ((mb_strlen($id) > 64)) {
            throw new \InvalidArgumentException('invalid length for $id when calling MenuItem., must be smaller than or equal to 64.');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name The name of the item.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 80)) {
            throw new \InvalidArgumentException('invalid length for $name when calling MenuItem., must be smaller than or equal to 80.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets name_translation
     *
     * @return array<string,string>|null
     */
    public function getNameTranslation()
    {
        return $this->container['name_translation'];
    }

    /**
     * Sets name_translation
     *
     * @param array<string,string>|null $name_translation Translation of the item name. Only support up to 1 translated language. Refer [Menu Translation](#section/Menu-Translation).
     *
     * @return self
     */
    public function setNameTranslation($name_translation)
    {
        if (is_null($name_translation)) {
            throw new \InvalidArgumentException('non-nullable name_translation cannot be null');
        }
        $this->container['name_translation'] = $name_translation;

        return $this;
    }

    /**
     * Gets available_status
     *
     * @return string
     */
    public function getAvailableStatus()
    {
        return $this->container['available_status'];
    }

    /**
     * Sets available_status
     *
     * @param string $available_status The status for the item. Refer to FAQs for more details about [availableStatus](#section/Menu/What-is-availableStatus).  > Note: In order to set an item as `\"UNAVAILABLE\"`, it is required to update both the `availableStatus` and `maxStock` fields, whereby the `maxStock` should be set to 0.
     *
     * @return self
     */
    public function setAvailableStatus($available_status)
    {
        if (is_null($available_status)) {
            throw new \InvalidArgumentException('non-nullable available_status cannot be null');
        }
        $allowedValues = $this->getAvailableStatusAllowableValues();
        if (!in_array($available_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'available_status', must be one of '%s'",
                    $available_status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['available_status'] = $available_status;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description The description of the item. There is a custom length limit of 2000 for `VN`.
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        if ((mb_strlen($description) > 300)) {
            throw new \InvalidArgumentException('invalid length for $description when calling MenuItem., must be smaller than or equal to 300.');
        }

        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets description_translation
     *
     * @return array<string,string>|null
     */
    public function getDescriptionTranslation()
    {
        return $this->container['description_translation'];
    }

    /**
     * Sets description_translation
     *
     * @param array<string,string>|null $description_translation Translation of the item description. Only support up to 1 translated language. Refer [Menu Translation](#section/Menu-Translation).
     *
     * @return self
     */
    public function setDescriptionTranslation($description_translation)
    {
        if (is_null($description_translation)) {
            throw new \InvalidArgumentException('non-nullable description_translation cannot be null');
        }
        $this->container['description_translation'] = $description_translation;

        return $this;
    }

    /**
     * Gets price
     *
     * @return int
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param int $price The item's price in minor format. For example: 1900 means $19 with `currency.exponent` as 2. Refer to [FAQ](#section/Menu/Is-the-menu-price-with-or-without-tax) to determine whether the pricing should be tax-inclusive or tax-exclusive.
     *
     * @return self
     */
    public function setPrice($price)
    {
        if (is_null($price)) {
            throw new \InvalidArgumentException('non-nullable price cannot be null');
        }
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets photos
     *
     * @return string[]|null
     */
    public function getPhotos()
    {
        return $this->container['photos'];
    }

    /**
     * Sets photos
     *
     * @param string[]|null $photos An array string for the item’s image URL link. Only 1 image is supported. Refer to FAQs for more details about [images formats](#section/Menu/What-are-the-recommended-formats-for-an-item-image).
     *
     * @return self
     */
    public function setPhotos($photos)
    {
        if (is_null($photos)) {
            throw new \InvalidArgumentException('non-nullable photos cannot be null');
        }
        $this->container['photos'] = $photos;

        return $this;
    }

    /**
     * Gets special_type
     *
     * @return string|null
     */
    public function getSpecialType()
    {
        return $this->container['special_type'];
    }

    /**
     * Sets special_type
     *
     * @param string|null $special_type The item's special Tag. Refer to FAQs for more details about [specialType](#section/Menu/What's-specialType).
     *
     * @return self
     */
    public function setSpecialType($special_type)
    {
        if (is_null($special_type)) {
            throw new \InvalidArgumentException('non-nullable special_type cannot be null');
        }
        $allowedValues = $this->getSpecialTypeAllowableValues();
        if (!in_array($special_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'special_type', must be one of '%s'",
                    $special_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['special_type'] = $special_type;

        return $this;
    }

    /**
     * Gets taxable
     *
     * @return bool|null
     */
    public function getTaxable()
    {
        return $this->container['taxable'];
    }

    /**
     * Sets taxable
     *
     * @param bool|null $taxable **For Indonesia only.** This field allows the configuration for an item to be marked as tax applicable, and marked item would then be included in a commercial invoice to consumers as per the government's regulations.
     *
     * @return self
     */
    public function setTaxable($taxable)
    {
        if (is_null($taxable)) {
            throw new \InvalidArgumentException('non-nullable taxable cannot be null');
        }
        $this->container['taxable'] = $taxable;

        return $this;
    }

    /**
     * Gets barcode
     *
     * @return string|null
     */
    public function getBarcode()
    {
        return $this->container['barcode'];
    }

    /**
     * Sets barcode
     *
     * @param string|null $barcode The barcode Number (GTIN). Max 64 allowed. GTIN must be 8, 12, 13, 14 numeric digits.
     *
     * @return self
     */
    public function setBarcode($barcode)
    {
        if (is_null($barcode)) {
            throw new \InvalidArgumentException('non-nullable barcode cannot be null');
        }
        if ((mb_strlen($barcode) > 64)) {
            throw new \InvalidArgumentException('invalid length for $barcode when calling MenuItem., must be smaller than or equal to 64.');
        }

        $this->container['barcode'] = $barcode;

        return $this;
    }

    /**
     * Gets selling_time_id
     *
     * @return string|null
     */
    public function getSellingTimeId()
    {
        return $this->container['selling_time_id'];
    }

    /**
     * Sets selling_time_id
     *
     * @param string|null $selling_time_id The selling time's ID for the item. This value overrides the category's selling time if it is different. Empty value implies the category's selling time will be applied.
     *
     * @return self
     */
    public function setSellingTimeId($selling_time_id)
    {
        if (is_null($selling_time_id)) {
            throw new \InvalidArgumentException('non-nullable selling_time_id cannot be null');
        }
        $this->container['selling_time_id'] = $selling_time_id;

        return $this;
    }

    /**
     * Gets max_stock
     *
     * @return int|null
     */
    public function getMaxStock()
    {
        return $this->container['max_stock'];
    }

    /**
     * Sets max_stock
     *
     * @param int|null $max_stock Available stocks under inventory for this item. Auto reduce when there is order placed for this item. Empty value implies no limit.  > Note: It is necessary to set `maxStock` to 0 if the `availableStatus` of the item is `\"UNAVAILABLE\"`. Item will be set to `\"AVAILABLE\"` if `maxStock` > 0.
     *
     * @return self
     */
    public function setMaxStock($max_stock)
    {
        if (is_null($max_stock)) {
            throw new \InvalidArgumentException('non-nullable max_stock cannot be null');
        }
        $this->container['max_stock'] = $max_stock;

        return $this;
    }

    /**
     * Gets sequence
     *
     * @return int|null
     */
    public function getSequence()
    {
        return $this->container['sequence'];
    }

    /**
     * Sets sequence
     *
     * @param int|null $sequence The sort or display order of the item within the menu.
     *
     * @return self
     */
    public function setSequence($sequence)
    {
        if (is_null($sequence)) {
            throw new \InvalidArgumentException('non-nullable sequence cannot be null');
        }
        $this->container['sequence'] = $sequence;

        return $this;
    }

    /**
     * Gets advanced_pricing
     *
     * @return \Grab\GrabfoodApiSdk\Model\AdvancedPricing|null
     */
    public function getAdvancedPricing()
    {
        return $this->container['advanced_pricing'];
    }

    /**
     * Sets advanced_pricing
     *
     * @param \Grab\GrabfoodApiSdk\Model\AdvancedPricing|null $advanced_pricing advanced_pricing
     *
     * @return self
     */
    public function setAdvancedPricing($advanced_pricing)
    {
        if (is_null($advanced_pricing)) {
            throw new \InvalidArgumentException('non-nullable advanced_pricing cannot be null');
        }
        $this->container['advanced_pricing'] = $advanced_pricing;

        return $this;
    }

    /**
     * Gets purchasability
     *
     * @return \Grab\GrabfoodApiSdk\Model\Purchasability|null
     */
    public function getPurchasability()
    {
        return $this->container['purchasability'];
    }

    /**
     * Sets purchasability
     *
     * @param \Grab\GrabfoodApiSdk\Model\Purchasability|null $purchasability purchasability
     *
     * @return self
     */
    public function setPurchasability($purchasability)
    {
        if (is_null($purchasability)) {
            throw new \InvalidArgumentException('non-nullable purchasability cannot be null');
        }
        $this->container['purchasability'] = $purchasability;

        return $this;
    }

    /**
     * Gets modifier_groups
     *
     * @return \Grab\GrabfoodApiSdk\Model\ModifierGroup[]|null
     */
    public function getModifierGroups()
    {
        return $this->container['modifier_groups'];
    }

    /**
     * Sets modifier_groups
     *
     * @param \Grab\GrabfoodApiSdk\Model\ModifierGroup[]|null $modifier_groups An array of the modifierGroup JSON objects. Max 30 allowed per item. Refer to [Modifier groups](#modifier-groups) for more information.
     *
     * @return self
     */
    public function setModifierGroups($modifier_groups)
    {
        if (is_null($modifier_groups)) {
            throw new \InvalidArgumentException('non-nullable modifier_groups cannot be null');
        }
        $this->container['modifier_groups'] = $modifier_groups;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


