<?php
/**
 * OrderPromo
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Grab\GrabfoodApiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Grab\GrabfoodApiSdk\Model;

use \ArrayAccess;
use \Grab\GrabfoodApiSdk\ObjectSerializer;

/**
 * OrderPromo Class Doc Comment
 *
 * @category Class
 * @package  Grab\GrabfoodApiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class OrderPromo implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OrderPromo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'code' => 'string',
        'description' => 'string',
        'name' => 'string',
        'promo_amount' => 'int',
        'mex_funded_ratio' => 'int',
        'mex_funded_amount' => 'int',
        'targeted_price' => 'int',
        'promo_amount_in_min' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'code' => null,
        'description' => null,
        'name' => null,
        'promo_amount' => 'int64',
        'mex_funded_ratio' => null,
        'mex_funded_amount' => 'int64',
        'targeted_price' => 'int64',
        'promo_amount_in_min' => 'int64'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'code' => false,
        'description' => false,
        'name' => false,
        'promo_amount' => false,
        'mex_funded_ratio' => false,
        'mex_funded_amount' => false,
        'targeted_price' => false,
        'promo_amount_in_min' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'code' => 'code',
        'description' => 'description',
        'name' => 'name',
        'promo_amount' => 'promoAmount',
        'mex_funded_ratio' => 'mexFundedRatio',
        'mex_funded_amount' => 'mexFundedAmount',
        'targeted_price' => 'targetedPrice',
        'promo_amount_in_min' => 'promoAmountInMin'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'code' => 'setCode',
        'description' => 'setDescription',
        'name' => 'setName',
        'promo_amount' => 'setPromoAmount',
        'mex_funded_ratio' => 'setMexFundedRatio',
        'mex_funded_amount' => 'setMexFundedAmount',
        'targeted_price' => 'setTargetedPrice',
        'promo_amount_in_min' => 'setPromoAmountInMin'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'code' => 'getCode',
        'description' => 'getDescription',
        'name' => 'getName',
        'promo_amount' => 'getPromoAmount',
        'mex_funded_ratio' => 'getMexFundedRatio',
        'mex_funded_amount' => 'getMexFundedAmount',
        'targeted_price' => 'getTargetedPrice',
        'promo_amount_in_min' => 'getPromoAmountInMin'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('promo_amount', $data ?? [], null);
        $this->setIfExists('mex_funded_ratio', $data ?? [], null);
        $this->setIfExists('mex_funded_amount', $data ?? [], null);
        $this->setIfExists('targeted_price', $data ?? [], null);
        $this->setIfExists('promo_amount_in_min', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets code
     *
     * @return string|null
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string|null $code Promo code applied in the order.
     *
     * @return self
     */
    public function setCode($code)
    {
        if (is_null($code)) {
            throw new \InvalidArgumentException('non-nullable code cannot be null');
        }
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Promo description.
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Name of the promotion.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets promo_amount
     *
     * @return int|null
     */
    public function getPromoAmount()
    {
        return $this->container['promo_amount'];
    }

    /**
     * Sets promo_amount
     *
     * @param int|null $promo_amount Promo amount applied in the order, in local currency. This amount is rounded into whole number.
     *
     * @return self
     */
    public function setPromoAmount($promo_amount)
    {
        if (is_null($promo_amount)) {
            throw new \InvalidArgumentException('non-nullable promo_amount cannot be null');
        }
        $this->container['promo_amount'] = $promo_amount;

        return $this;
    }

    /**
     * Gets mex_funded_ratio
     *
     * @return int|null
     */
    public function getMexFundedRatio()
    {
        return $this->container['mex_funded_ratio'];
    }

    /**
     * Sets mex_funded_ratio
     *
     * @param int|null $mex_funded_ratio The merchant's funded ratio of the promo in percentage.
     *
     * @return self
     */
    public function setMexFundedRatio($mex_funded_ratio)
    {
        if (is_null($mex_funded_ratio)) {
            throw new \InvalidArgumentException('non-nullable mex_funded_ratio cannot be null');
        }
        $this->container['mex_funded_ratio'] = $mex_funded_ratio;

        return $this;
    }

    /**
     * Gets mex_funded_amount
     *
     * @return int|null
     */
    public function getMexFundedAmount()
    {
        return $this->container['mex_funded_amount'];
    }

    /**
     * Sets mex_funded_amount
     *
     * @param int|null $mex_funded_amount The merchant's promo fund in the minor unit. Calculated based on merchant funded ratio.
     *
     * @return self
     */
    public function setMexFundedAmount($mex_funded_amount)
    {
        if (is_null($mex_funded_amount)) {
            throw new \InvalidArgumentException('non-nullable mex_funded_amount cannot be null');
        }
        $this->container['mex_funded_amount'] = $mex_funded_amount;

        return $this;
    }

    /**
     * Gets targeted_price
     *
     * @return int|null
     */
    public function getTargetedPrice()
    {
        return $this->container['targeted_price'];
    }

    /**
     * Sets targeted_price
     *
     * @param int|null $targeted_price The subtotal of the order basket in minor unit.
     *
     * @return self
     */
    public function setTargetedPrice($targeted_price)
    {
        if (is_null($targeted_price)) {
            throw new \InvalidArgumentException('non-nullable targeted_price cannot be null');
        }
        $this->container['targeted_price'] = $targeted_price;

        return $this;
    }

    /**
     * Gets promo_amount_in_min
     *
     * @return int|null
     */
    public function getPromoAmountInMin()
    {
        return $this->container['promo_amount_in_min'];
    }

    /**
     * Sets promo_amount_in_min
     *
     * @param int|null $promo_amount_in_min Promo amount applied in the order in minor unit.
     *
     * @return self
     */
    public function setPromoAmountInMin($promo_amount_in_min)
    {
        if (is_null($promo_amount_in_min)) {
            throw new \InvalidArgumentException('non-nullable promo_amount_in_min cannot be null');
        }
        $this->container['promo_amount_in_min'] = $promo_amount_in_min;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


