<?php
/**
 * OutOfStockInstruction
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Grab\GrabfoodApiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Grab\GrabfoodApiSdk\Model;

use \ArrayAccess;
use \Grab\GrabfoodApiSdk\ObjectSerializer;

/**
 * OutOfStockInstruction Class Doc Comment
 *
 * @category Class
 * @description An JSON object that indicates the instructions to be taken by the merchant when the item is out of stock.
 * @package  Grab\GrabfoodApiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class OutOfStockInstruction implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'outOfStockInstruction';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'title' => 'string',
        'instruction_type' => 'string',
        'replacement_item_id' => 'string',
        'replacement_grab_item_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'title' => null,
        'instruction_type' => null,
        'replacement_item_id' => null,
        'replacement_grab_item_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'title' => false,
        'instruction_type' => false,
        'replacement_item_id' => false,
        'replacement_grab_item_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'title' => 'title',
        'instruction_type' => 'instructionType',
        'replacement_item_id' => 'replacementItemID',
        'replacement_grab_item_id' => 'replacementGrabItemID'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'title' => 'setTitle',
        'instruction_type' => 'setInstructionType',
        'replacement_item_id' => 'setReplacementItemId',
        'replacement_grab_item_id' => 'setReplacementGrabItemId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'title' => 'getTitle',
        'instruction_type' => 'getInstructionType',
        'replacement_item_id' => 'getReplacementItemId',
        'replacement_grab_item_id' => 'getReplacementGrabItemId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const INSTRUCTION_TYPE_REMOVE = 'REMOVE';
    public const INSTRUCTION_TYPE_CANCEL = 'CANCEL';
    public const INSTRUCTION_TYPE_SPECIFIC_ITEM = 'SPECIFIC_ITEM';
    public const INSTRUCTION_TYPE_CONTACT = 'CONTACT';
    public const INSTRUCTION_TYPE_UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getInstructionTypeAllowableValues()
    {
        return [
            self::INSTRUCTION_TYPE_REMOVE,
            self::INSTRUCTION_TYPE_CANCEL,
            self::INSTRUCTION_TYPE_SPECIFIC_ITEM,
            self::INSTRUCTION_TYPE_CONTACT,
            self::INSTRUCTION_TYPE_UNKNOWN_DEFAULT_OPEN_API,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('instruction_type', $data ?? [], null);
        $this->setIfExists('replacement_item_id', $data ?? [], null);
        $this->setIfExists('replacement_grab_item_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getInstructionTypeAllowableValues();
        if (!is_null($this->container['instruction_type']) && !in_array($this->container['instruction_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'instruction_type', must be one of '%s'",
                $this->container['instruction_type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title The short instruction message.
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets instruction_type
     *
     * @return string|null
     */
    public function getInstructionType()
    {
        return $this->container['instruction_type'];
    }

    /**
     * Sets instruction_type
     *
     * @param string|null $instruction_type Type of out-of-stock instruction chosen by customer. `CONTACT` is disabled by default, kindly reach out to your integration manager if you wish to receive this instruction.
     *
     * @return self
     */
    public function setInstructionType($instruction_type)
    {
        if (is_null($instruction_type)) {
            throw new \InvalidArgumentException('non-nullable instruction_type cannot be null');
        }
        $allowedValues = $this->getInstructionTypeAllowableValues();
        if (!in_array($instruction_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'instruction_type', must be one of '%s'",
                    $instruction_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['instruction_type'] = $instruction_type;

        return $this;
    }

    /**
     * Gets replacement_item_id
     *
     * @return string|null
     */
    public function getReplacementItemId()
    {
        return $this->container['replacement_item_id'];
    }

    /**
     * Sets replacement_item_id
     *
     * @param string|null $replacement_item_id The preferred item's ID in the partner system. Only applicable when the instructionType is `SPECIFIC_ITEM`.
     *
     * @return self
     */
    public function setReplacementItemId($replacement_item_id)
    {
        if (is_null($replacement_item_id)) {
            throw new \InvalidArgumentException('non-nullable replacement_item_id cannot be null');
        }
        $this->container['replacement_item_id'] = $replacement_item_id;

        return $this;
    }

    /**
     * Gets replacement_grab_item_id
     *
     * @return string|null
     */
    public function getReplacementGrabItemId()
    {
        return $this->container['replacement_grab_item_id'];
    }

    /**
     * Sets replacement_grab_item_id
     *
     * @param string|null $replacement_grab_item_id The preferred item's ID in the Grab system. Only applicable when the instructionType is `SPECIFIC_ITEM`.
     *
     * @return self
     */
    public function setReplacementGrabItemId($replacement_grab_item_id)
    {
        if (is_null($replacement_grab_item_id)) {
            throw new \InvalidArgumentException('non-nullable replacement_grab_item_id cannot be null');
        }
        $this->container['replacement_grab_item_id'] = $replacement_grab_item_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


