<?php
/**
 * PushIntegrationStatusWebhookRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Grab\GrabfoodApiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Grab\GrabfoodApiSdk\Model;

use \ArrayAccess;
use \Grab\GrabfoodApiSdk\ObjectSerializer;

/**
 * PushIntegrationStatusWebhookRequest Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  Grab\GrabfoodApiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PushIntegrationStatusWebhookRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PushIntegrationStatusWebhookRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'partner_merchant_id' => 'string',
        'grab_merchant_id' => 'string',
        'integration_status' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'partner_merchant_id' => null,
        'grab_merchant_id' => null,
        'integration_status' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'partner_merchant_id' => false,
        'grab_merchant_id' => false,
        'integration_status' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'partner_merchant_id' => 'partnerMerchantID',
        'grab_merchant_id' => 'grabMerchantID',
        'integration_status' => 'integrationStatus'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'partner_merchant_id' => 'setPartnerMerchantId',
        'grab_merchant_id' => 'setGrabMerchantId',
        'integration_status' => 'setIntegrationStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'partner_merchant_id' => 'getPartnerMerchantId',
        'grab_merchant_id' => 'getGrabMerchantId',
        'integration_status' => 'getIntegrationStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const INTEGRATION_STATUS_INACTIVE = 'INACTIVE';
    public const INTEGRATION_STATUS_ACTIVE = 'ACTIVE';
    public const INTEGRATION_STATUS_SYNCING = 'SYNCING';
    public const INTEGRATION_STATUS_FAILED = 'FAILED';
    public const INTEGRATION_STATUS_UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getIntegrationStatusAllowableValues()
    {
        return [
            self::INTEGRATION_STATUS_INACTIVE,
            self::INTEGRATION_STATUS_ACTIVE,
            self::INTEGRATION_STATUS_SYNCING,
            self::INTEGRATION_STATUS_FAILED,
            self::INTEGRATION_STATUS_UNKNOWN_DEFAULT_OPEN_API,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('partner_merchant_id', $data ?? [], null);
        $this->setIfExists('grab_merchant_id', $data ?? [], null);
        $this->setIfExists('integration_status', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['partner_merchant_id'] === null) {
            $invalidProperties[] = "'partner_merchant_id' can't be null";
        }
        if ($this->container['grab_merchant_id'] === null) {
            $invalidProperties[] = "'grab_merchant_id' can't be null";
        }
        if ($this->container['integration_status'] === null) {
            $invalidProperties[] = "'integration_status' can't be null";
        }
        $allowedValues = $this->getIntegrationStatusAllowableValues();
        if (!is_null($this->container['integration_status']) && !in_array($this->container['integration_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'integration_status', must be one of '%s'",
                $this->container['integration_status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets partner_merchant_id
     *
     * @return string
     */
    public function getPartnerMerchantId()
    {
        return $this->container['partner_merchant_id'];
    }

    /**
     * Sets partner_merchant_id
     *
     * @param string $partner_merchant_id The merchant's ID that is on the partner's database.
     *
     * @return self
     */
    public function setPartnerMerchantId($partner_merchant_id)
    {
        if (is_null($partner_merchant_id)) {
            throw new \InvalidArgumentException('non-nullable partner_merchant_id cannot be null');
        }
        $this->container['partner_merchant_id'] = $partner_merchant_id;

        return $this;
    }

    /**
     * Gets grab_merchant_id
     *
     * @return string
     */
    public function getGrabMerchantId()
    {
        return $this->container['grab_merchant_id'];
    }

    /**
     * Sets grab_merchant_id
     *
     * @param string $grab_merchant_id The merchant's ID that is in GrabFood's database.
     *
     * @return self
     */
    public function setGrabMerchantId($grab_merchant_id)
    {
        if (is_null($grab_merchant_id)) {
            throw new \InvalidArgumentException('non-nullable grab_merchant_id cannot be null');
        }
        $this->container['grab_merchant_id'] = $grab_merchant_id;

        return $this;
    }

    /**
     * Gets integration_status
     *
     * @return string
     */
    public function getIntegrationStatus()
    {
        return $this->container['integration_status'];
    }

    /**
     * Sets integration_status
     *
     * @param string $integration_status The store integration status. - `INACTIVE`: Merchant integration deactivated - `ACTIVE`: Merchant integration activated - `SYNCING`: Merchant integration is syncing - `FAILED`: Merchant integration has failed
     *
     * @return self
     */
    public function setIntegrationStatus($integration_status)
    {
        if (is_null($integration_status)) {
            throw new \InvalidArgumentException('non-nullable integration_status cannot be null');
        }
        $allowedValues = $this->getIntegrationStatusAllowableValues();
        if (!in_array($integration_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'integration_status', must be one of '%s'",
                    $integration_status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['integration_status'] = $integration_status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


